/**
 * Clavix v4.8: Verification System Types
 *
 * Type definitions for the checklist verification system that ensures
 * checklists generated by improve mode are verified after implementation.
 * v4.11: Updated to use DepthLevel instead of fast/deep source distinction.
 */

import { PromptIntent, DepthLevel } from '../core/intelligence/types.js';

// =============================================================================
// Checklist Item Types
// =============================================================================

/**
 * Category of checklist item
 */
export type ChecklistCategory = 'validation' | 'edge-case' | 'risk';

/**
 * How the checklist item can be verified
 */
export type VerificationType =
  | 'automated' // CLI command can verify (tests, build, lint)
  | 'semi-automated' // CLI runs, agent interprets output
  | 'manual'; // Agent reviews code/behavior

/**
 * A single item from the checklist
 */
export interface ChecklistItem {
  /** Unique identifier (e.g., "validation-1", "edge-case-2") */
  id: string;

  /** Category of the item */
  category: ChecklistCategory;

  /** Item description text */
  content: string;

  /** Optional grouping (e.g., "Functionality", "Robustness") */
  group?: string;

  /** How this item should be verified */
  verificationType: VerificationType;
}

/**
 * Parsed checklist from a prompt file
 */
export interface ParsedChecklist {
  /** Validation checklist items (☐ items from deep mode) */
  validationItems: ChecklistItem[];

  /** Edge cases to consider */
  edgeCases: ChecklistItem[];

  /** Risk/what could go wrong items */
  risks: ChecklistItem[];

  /** Whether the prompt has any checklist */
  hasChecklist: boolean;

  /** Total number of items across all categories */
  totalItems: number;
}

// =============================================================================
// Verification Hook Types
// =============================================================================

/**
 * Type of verification hook
 */
export type HookType = 'test' | 'build' | 'lint' | 'typecheck' | 'custom';

/**
 * A CLI hook for automated verification
 */
export interface VerificationHook {
  /** Hook identifier */
  name: HookType;

  /** Display name */
  displayName: string;

  /** Command to execute */
  command: string;

  /** Regex pattern to match success */
  successPattern?: RegExp;

  /** Regex pattern to match failure */
  failurePattern?: RegExp;

  /** Timeout in milliseconds */
  timeout: number;
}

/**
 * Result of running a verification hook
 */
export interface HookResult {
  /** Hook that was run */
  hook: VerificationHook;

  /** Whether the hook succeeded */
  success: boolean;

  /** Exit code of the command */
  exitCode: number;

  /** Command output (stdout + stderr) */
  output: string;

  /** Confidence in the result */
  confidence: VerificationConfidence;

  /** Execution time in milliseconds */
  executionTimeMs: number;

  /** Error message if hook failed to run */
  error?: string;
}

/**
 * Detected hooks for a project
 */
export interface DetectedHooks {
  /** Available hooks */
  hooks: VerificationHook[];

  /** Package manager detected */
  packageManager: 'npm' | 'yarn' | 'pnpm' | 'unknown';

  /** Whether a package.json was found */
  hasPackageJson: boolean;
}

// =============================================================================
// Verification Result Types
// =============================================================================

/**
 * Status of a verification item
 */
export type VerificationStatus =
  | 'pending' // Not yet checked
  | 'passed' // Verified successfully
  | 'failed' // Verification failed
  | 'skipped' // Intentionally skipped
  | 'not-applicable'; // Does not apply

/**
 * Confidence level in the verification result
 */
export type VerificationConfidence = 'high' | 'medium' | 'low';

/**
 * Method used for verification
 */
export type VerificationMethod = 'automated' | 'semi-automated' | 'manual';

/**
 * Result of verifying a single checklist item
 */
export interface VerificationResult {
  /** ID of the checklist item */
  itemId: string;

  /** Verification status */
  status: VerificationStatus;

  /** Method used for verification */
  method: VerificationMethod;

  /** Confidence in the result */
  confidence: VerificationConfidence;

  /** Evidence of verification (command output or agent reasoning) */
  evidence?: string;

  /** Reason for failed/skipped status */
  reason?: string;

  /** Timestamp of verification */
  verifiedAt: string;
}

// =============================================================================
// Verification Report Types
// =============================================================================

/**
 * Overall status of the verification report
 */
export type ReportStatus =
  | 'pending' // Not started
  | 'in-progress' // Some items verified
  | 'completed' // All items verified
  | 'requires-attention'; // Has failed items

/**
 * Summary statistics for verification
 */
export interface VerificationSummary {
  /** Total number of items */
  total: number;

  /** Number of passed items */
  passed: number;

  /** Number of failed items */
  failed: number;

  /** Number of skipped items */
  skipped: number;

  /** Number of not-applicable items */
  notApplicable: number;

  /** Coverage percentage (passed / (total - skipped - notApplicable)) */
  coveragePercent: number;

  /** Number of automated checks */
  automatedChecks: number;

  /** Number of manual checks */
  manualChecks: number;
}

/**
 * Full verification report
 */
export interface VerificationReport {
  /** Report version (v4.11: Allow 2.0 for unified storage format) */
  version: '1.0' | '2.0';

  /** ID of the prompt being verified */
  promptId: string;

  /** v4.11: Depth level used for this prompt (replaces source: 'fast' | 'deep') */
  depthUsed: DepthLevel;

  /** When verification started */
  startedAt: string;

  /** When verification completed (all items done) */
  completedAt?: string;

  /** Overall status */
  status: ReportStatus;

  /** All checklist items */
  items: ChecklistItem[];

  /** Verification results for each item */
  results: VerificationResult[];

  /** Summary statistics */
  summary: VerificationSummary;

  /** Detected hooks used for automated verification */
  detectedHooks?: DetectedHooks;
}

// =============================================================================
// Basic Checklist Generator Types (for fast mode)
// =============================================================================

/**
 * Intent-to-checklist mapping entry
 */
export interface IntentChecklist {
  /** The intent type */
  intent: PromptIntent;

  /** Checklist items for this intent */
  items: Array<{
    content: string;
    group?: string;
    verificationType: VerificationType;
  }>;
}

// =============================================================================
// Extended PromptMetadata (for integration with prompt-manager)
// =============================================================================

/**
 * Additional fields for PromptMetadata to support verification
 */
export interface VerificationMetadata {
  /** Whether verification is required for this prompt */
  verificationRequired?: boolean;

  /** Whether the prompt has been verified */
  verified?: boolean;

  /** Timestamp of last verification */
  lastVerifiedAt?: string;

  /** Path to verification report file */
  verificationReportPath?: string;
}
